#!/usr/bin/env php
<?php

// Generates a `packages.json` file from composer.json files in path
// repositories. .git folders are not copied to the temporary directory used by
// Automatic Updates, so Composer cannot use branch info for versions during
// updates. If we just replaced path repositories with package repositories in
// composer.json, the xb_page.yml file would not be copied.

$read_json = function (string $file): array {
  $data = file_get_contents($file);
  return json_decode($data, TRUE, flags: JSON_THROW_ON_ERROR);
};

$data = array_merge_recursive(
  $read_json('repos/drupal/drupal_cms/project_template/composer.json'),
  $read_json('repos/drupal/drupal_cms/dev.composer.json'),
);

array_walk($data['repositories'], function (array &$repository): void {
  if ($repository['type'] === 'path') {
    $repository['url'] = 'repos/drupal/drupal_cms/' . $repository['url'];
  }
});

$packages = [];
foreach ($data['repositories'] as $key => $repository) {
  if ($repository['type'] === 'path') {
    $package = $read_json($repository['url'] . '/composer.json');
    if (!isset($package['version'])) {
      $package['version'] = 'dev-' . rtrim(`git -C $repository[url] branch -r | grep "origin/HEAD" | cut -f 3 -d '/'`);
    }
    $package['dist'] = [
      'type' => 'path',
      'url' => $repository['url'],
    ];
    $packages[$package['name']] = [
      $package['version'] => $package,
    ];
  }
}
echo json_encode(['packages' => $packages], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
