#!/usr/bin/env php
<?php

// Generates the development-ready `composer.json` file by merging our
// development requirements into the project template. This script must
// be run from the repository root.

$read_json = function (string $file): array {
  $data = file_get_contents($file);
  return json_decode($data, TRUE, flags: JSON_THROW_ON_ERROR);
};

// From \Drupal\Component\Utility\NestedArray::mergeDeep().
$merge_deep = function (array ...$arrays) use (&$merge_deep): array {
  $result = [];
  foreach ($arrays as $array) {
    foreach ($array as $key => $value) {
      // Recurse when both values are arrays.
      if (isset($result[$key]) && is_array($result[$key]) && is_array($value)) {
        $result[$key] = $merge_deep($result[$key], $value);
      }
      // Otherwise, use the latter value, overriding any previous value.
      else {
        $result[$key] = $value;
      }
    }
  }
  return $result;
};

$base = $read_json('repos/drupal/drupal_cms/project_template/composer.json');
$dev = $read_json('repos/drupal/drupal_cms/dev.composer.json');
$drupalforge = $read_json('drupalforge.composer.json');
$data = $merge_deep($base, $dev, $drupalforge);

array_walk($data['repositories'], function (array &$repository): void {
  if ($repository['type'] === 'path') {
    $repository['url'] = 'repos/drupal/drupal_cms/' . $repository['url'];
  }
});

// Make packages.drupal.org the lowest-priority repository, which will force the
// components' local path repositories to take precedence.
$repository = $data['repositories']['drupal'];
unset($data['repositories']['drupal']);
$data['repositories']['drupal'] = $repository;

echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
