#!/usr/bin/env php
<?php

// Runs the installer steps prior to recipe application.

$_SERVER['HTTP_USER_AGENT'] = 'Drupal Forge';
$_GET['profile'] = 'drupal_cms_installer';
$_GET['langcode'] = 'en';
$_GET['recipes'] = '';
$_GET['site_name'] = 'Drupal CMS';

register_shutdown_function('_install_drupal_cms_profile_modules');

function _install_drupal_cms_profile_modules() {
  global $install_state;
  if ($install_state['base_system_verified']) {
    $batch = install_profile_modules($install_state);
    $context = ['results' => []];
    foreach ($batch['operations'] as $step) {
      call_user_func_array($step[0], array_merge($step[1], [&$context]));
    }
    \Drupal::state()->set('drupal_cms_profile.profile_modules_installed', TRUE);
  }
}

chdir(dirname(__DIR__) . '/web/core');
include 'install.php';
