include:
  - remote: 'https://gitlab.lakedrops.com/gitlab-ci-cd/drupal/-/raw/main/mr-proposed-changes.yml'
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'
BuildApp:
  extends: '.mr-proposed-changes'
  script:
    - cd build
    - npm update --save
    - npm run all
variables:
  _CSPELL_IGNORE_PATHS: '"build/", "css/", "js/", "webpack/", "**/eca.eca.*.yml", "**/eca.model.*.yml", "**/ConverterTest.php", "tests/**/*.js"'
  SKIP_ESLINT: '1'
  SKIP_STYLELINT: '1'
  OPT_IN_TEST_PREVIOUS_MAJOR: 1
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 0
  RUN_JOB_UPGRADE_STATUS: 0
cspell:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
phpstan (next minor):
  allow_failure: false
phpstan (next major):
  allow_failure: false
phpunit (previous major):
  allow_failure: false
phpunit (next minor):
  allow_failure: false
phpunit (next major):
  allow_failure: false
upgrade status:
  allow_failure: false
