editoria11y.settings:
  type: config_object
  label: 'Editoria11y Settings'
  mapping:
    content_root:
      type: string
      label: 'Check elements in these containers'
    assertiveness:
      type: string
      label: 'Alert panel assertiveness'
    no_load:
      type: string
      label: 'Do not run if these elements are on the page'
    ignore_all_if_absent:
      type: string
      label: 'Suppress all alerts if none of these elements are present'
    ignore_elements:
      type: string
      label: 'Do not run tests on these containers'
    panel_no_cover:
      type: string
      label: 'Move toggle to avoid colliding with these widgets'
    embedded_content_warning:
      type: string
      label: 'Full check should warn on these elements with embedded uncheckable content'
    download_links:
      type: string
      label: 'These links download a document or image and need a manual review'
    link_strings_new_windows:
      type: string
      label: 'Strings that indicate a link opens in a new window'
    ignore_link_strings:
      type: string
      label: 'Remove these strings from link text before checking for bad link text'
    link_ignore_selector:
      type: string
      label: 'Remove strings in this selector before checking for bad link text'
    hidden_handlers:
      type: string
      label: 'Hidden elements in these containers will be revealed by theme JS on request via a dispatched event'
    ed11y_theme:
      type: string
      label: 'Color scheme for panel and tooltips'
    shadow_components:
      type: string
      label: 'Web components the checker should check'
    disable_sync:
      type: boolean
      label: 'Disables dashboard and synchronized marking of elements as OK'
    preserve_params:
      type: string
      label: 'URL query parameters that should be recorded as separate pages'
    redundant_prefix:
      type: string
      label: 'Remove string from URL for dashboard page links'
    custom_tests:
      type: integer
      label: 'Number of custom test finished events the checker should wait for'
    disable_live:
      type: boolean
      label: 'Disables live editor checking'
    live_h_inherit:
      type: string
      label: 'Selector for frontend-context editors that should inherit the document outline'
    live_h2:
      type: string
      label: 'Selector for editors where their first heading should be h2'
    live_h3:
      type: string
      label: 'Selector for editors where their first heading should be h3'
    live_h4:
      type: string
      label: 'Selector for editors where their first heading should be h4'
    hide_edit_links:
      type: string
      label: 'Selectors for components where edit links are meaningless on tips'
