name: starshot
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
ddev_version_constraint: '>= 1.24.0'
hooks:
  post-start:
    # Set up debugging.
    - exec: 'test -f .vscode/launch.json || (mkdir -p .vscode && cp .ddev/launch.json .vscode/)'
    # Get a local copy of Drupal CMS and check out the default branch.
    # Patch for issue #3496399.
    - exec: 'cd repos/drupal/drupal_cms && test -n "$(ls -A)" || (git submodule update --init --remote --recursive && git checkout $(git branch -r | grep "origin/HEAD" | cut -f 3 -d "/"))'
    # If needed, regenerate `composer.json` and install dependencies.
    # @see homeadditions/bin/generate-composer-json
    - exec: 'test -f composer.lock || (.devpanel/generate-composer-json > composer.json && composer install)'
    # The installer is part of the project template, so symlink it into the web root.
    # It needs to be a relative symlink, or it will break Package Manager.
    - exec: 'ln -s -f $(realpath -s --relative-to=$DDEV_DOCROOT/profiles repos/drupal/drupal_cms/project_template/web/profiles/drupal_cms_installer) $DDEV_DOCROOT/profiles'
    # Install JavaScript dependencies if needed. The `--foreground-scripts`
    # option is needed to ensure the Cypress binary is actually downloaded;
    # see the warning about Node.js Snap for Linux at
    # https://docs.cypress.io/guides/getting-started/installing-cypress.
    - exec: 'cd repos/drupal/drupal_cms && test -d node_modules || npm clean-install --foreground-scripts'
    # Build Experience Builder's JavaScript bundle, if needed.
    - exec: 'XB_UI_PATH=$DDEV_DOCROOT/modules/contrib/experience_builder/ui; test -d $XB_UI_PATH/dist || ( npm --prefix $XB_UI_PATH install && npm --prefix $XB_UI_PATH run build )'
    # Copy recipes cache. Not working now, so patch only.
    - exec: 'grep -qxF "/project_template/web/profiles/drupal_cms_installer/cache/*" .git/modules/repos/drupal/drupal_cms/info/exclude || echo "/project_template/web/profiles/drupal_cms_installer/cache/*" >> .git/modules/repos/drupal/drupal_cms/info/exclude'
    #- exec: 'test -d web/profiles/drupal_cms_installer/cache && test -z "$(git status --porcelain repos/drupal/drupal_cms)" && cp -n .devpanel/drupal_cms_cache/* web/profiles/drupal_cms_installer/cache && cd repos/drupal/drupal_cms && (git merge-base --is-ancestor 4312efcda4ea322a7be4a64b000d07c34ff031e8 HEAD || git apply $DDEV_COMPOSER_ROOT/patches/drupal/drupal_cms/373.patch) || true'
    - exec: 'cd repos/drupal/drupal_cms && (git merge-base --is-ancestor 4312efcda4ea322a7be4a64b000d07c34ff031e8 HEAD 2> /dev/null || git apply $DDEV_COMPOSER_ROOT/patches/drupal/drupal_cms/373.patch) || true'
    # Create the private files directory.
    - exec: 'test -d private || mkdir private'
    # Add the private files path to settings.php.
    - exec: 'grep -qxF "\$settings[''file_private_path''] = ''../private'';" web/sites/default/settings.php || echo "\$settings[''file_private_path''] = ''../private'';" >> web/sites/default/settings.php'
    # Pre-install starter recipe.
    - exec: 'test -d recipes/drupal_cms_starter && test -z "$(drush status --fields=bootstrap)" && .devpanel/install > /dev/null && drush ev "require_once ''core/includes/install.core.inc''; install_core_entity_type_definitions();" && until drush recipe ../recipes/drupal_cms_starter; do :; done && drush -n pmu drupal_cms_installer && drush cr || true'
web_environment:
  # For faster performance, don't audit dependencies automatically.
  - COMPOSER_NO_AUDIT=1
  # To display its UI, Cypress needs to be able to talk to an X11 server
  # running on the host machine.
  # - DISPLAY=host.docker.internal:0
  # Download Cypress to a directory that won't be blown away every time the
  # project is restarted.
  - CYPRESS_CACHE_FOLDER=/var/www/html/.cache/cypress
  - DRUPAL_CMS_INSTALLER_WRITE_CACHE=1
  # Use the DDEV-provided database to run PHPUnit tests.
  - SIMPLETEST_DB=$DDEV_DATABASE_FAMILY://db:db@db/db
  - SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL
webimage_extra_packages:
  # Add Cypress' system dependencies.
  # See https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - xauth
  - xvfb
  # Additional browsers for Cypress to test against.
  - chromium
  - firefox-esr
