name: starshot
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
corepack_enable: false
ddev_version_constraint: '>= 1.24.0'
hooks:
  post-start:
    # Set up debugging.
    - exec: 'test -f .vscode/launch.json || (mkdir -p .vscode && cp .ddev/launch.json .vscode/)'
    # Run initial setup tasks.
    - exec: '.devpanel/init.sh'
web_environment:
  # For faster performance, don't audit dependencies automatically.
  - COMPOSER_NO_AUDIT=1
  # To display its UI, Cypress needs to be able to talk to an X11 server
  # running on the host machine.
  # - DISPLAY=host.docker.internal:0
  # Download Cypress to a directory that won't be blown away every time the
  # project is restarted.
  - CYPRESS_CACHE_FOLDER=/var/www/html/.cache/cypress
  # Use the DDEV-provided database to run PHPUnit tests.
  - SIMPLETEST_DB=$DDEV_DATABASE_FAMILY://db:db@db/db
  - SIMPLETEST_BASE_URL=$DDEV_PRIMARY_URL
  # Set up DevPanel variables.
  - APP_ROOT=$DDEV_COMPOSER_ROOT
  - WEB_ROOT=$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT
  - DB_HOST=db
  - DB_PORT=3306
  - DB_USER=db
  - DB_PASSWORD=db
  - DB_NAME=db
webimage_extra_packages:
  # Add Cypress' system dependencies.
  # See https://docs.cypress.io/guides/getting-started/installing-cypress#UbuntuDebian
  - libgtk2.0-0
  - libgtk-3-0
  - libgbm-dev
  - libnotify-dev
  - libnss3
  - libxss1
  - libasound2
  - libxtst6
  - xauth
  - xvfb
  # Additional browsers for Cypress to test against.
  - chromium
  - firefox-esr
