name: Docker build and push template
on:
  push:
    branches:
      - 'feature/*'
env:
  APP_ROOT: '/var/www/html'        
  WEB_ROOT: '/var/www/html/web'
  SERVER_NAME: 'localhost'
  CODES_ENABLE: 'no'
  DB_HOST: mysql
  DB_PORT: 3306
  DB_ROOT_PASSWORD: root
  DB_NAME: drupaldb
  DB_USER: user
  DB_PASSWORD: pass

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: devpanel/php:8.3-base
      options: --user root
      ports:
        - 80:80
    defaults:
      run:
        shell: bash
        working-directory: /var/www/html
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Create new user and switch
      run: |
        sudo -u www whoami
        echo ${USER}

    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: repo

    - name: Move repository
      run: |
        sudo -u www whoami
        echo ${USER}
        sudo rm -rf /var/www/html
        sudo mkdir -p /var/www/html
        mv /__w/starshot/starshot/repo/* /var/www/html
        mv /__w/starshot/starshot/repo/.* /var/www/html || true  # Moves hidden files, ignoring any errors if no hidden files exist
     

    - name: Setup Drupal
      run: |
        set -e
        git config --global --add safe.directory '/var/www/html'
        pwd 
        cd $APP_ROOT
        sudo chown -R www:www $APP_ROOT
        mkdir -p $WEB_ROOT
        ls -al
        ls -al $APP_ROOT/repos/drupal/drupal_cms
        export
        echo ${USER}
        sudo cp /templates/000-default.conf /etc/apache2/sites-enabled/000-default.conf
        [ ! -z "$APP_ROOT" ] &&  sudo sed -i "s|{{APP_ROOT}}|${APP_ROOT}|" /etc/apache2/sites-enabled/000-default.conf
        [ ! -z "$WEB_ROOT" ] &&  sudo sed -i "s|{{WEB_ROOT}}|${WEB_ROOT}|" /etc/apache2/sites-enabled/000-default.conf
        [ ! -z "$SERVER_NAME" ] && sudo sed -i "s|{{SERVER_NAME}}|${SERVER_NAME}|" /etc/apache2/sites-enabled/000-default.conf
        cat /etc/apache2/sites-enabled/000-default.conf

        sudo service apache2 start
 
        # bash .devpanel/custom_package_installer.sh
        # bash .devpanel/init.sh
        ls -al $WEB_ROOT
        curl -I http://localhost || echo "Failed to make HTTP request to port 80"
        
