name: Docker build and push template
on:
  push:
    branches:
      - main
      - develop
      - test/*
jobs:
  build-application:
    runs-on: ubuntu-latest
    services:
      webserver:
        image: devpanel/php:8.3-base
        env:
          APP_ROOT: '/devpanel/build'        
          WEB_ROOT: '/devpanel/build/web'
          CODES_USER_DATA_DIR: '/devpanel/build/.vscode'
          CODES_WORKING_DIR: '/devpanel/build'
          APACHE_RUN_USER: 'www'
          APACHE_RUN_GROUP: 'www'
          CODES_ENABLE: 'yes'
          DB_HOST: mysql
          DB_PORT: 3306
          DB_ROOT_PASSWORD: root
          DB_NAME: drupaldb
          DB_USER: user
          DB_PASSWORD: password
        ports:
          - 80:80
        volumes:
          - ${{ github.workspace }}:/app/  # Mounting the checked-out code
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Set up Docker Environment
      uses: docker/setup-buildx-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Drupal
      run: |
        echo "PREPARE DIR FOR INSTALL" 
        docker exec ${{ job.services.webserver.id }} bash -c "sudo rm -rf \$APP_ROOT && sudo mkdir -p \$APP_ROOT"
        docker exec ${{ job.services.webserver.id }} bash -c "sudo cp -r /app/. \$APP_ROOT/." 
        docker exec ${{ job.services.webserver.id }} bash -c "sudo chown -R www:www \$APP_ROOT"
        docker exec ${{ job.services.webserver.id }} bash -c "export && cd \$APP_ROOT && ls -al"
        echo "SET UP GIT" 
        docker exec ${{ job.services.webserver.id }} bash -c "git config --global --add safe.directory \$APP_ROOT"
        docker exec ${{ job.services.webserver.id }} bash -c "git config --global --add safe.directory \$APP_ROOT/repos/drupal/drupal_cms"
        echo "INSTALL CUSTOM PACKAGE" 
        docker exec ${{ job.services.webserver.id }} bash -c "\$APP_ROOT/.devpanel/custom_package_installer.sh" 
        echo "INSTALL DRUPAL" 
        docker exec ${{ job.services.webserver.id }} bash -c "cd \$APP_ROOT && ls -al"
        docker exec ${{ job.services.webserver.id }} bash -c "\$APP_ROOT/.devpanel/init.sh" 
        echo "DUMPS DATABASE + STATIC FILE" 
        docker exec ${{ job.services.webserver.id }} bash -c "\$APP_ROOT/.devpanel/quickstart/create_quickstart.sh" 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set env to testing environment
      run: |
        echo "IMAGE_TAG=devpanel/starshot:develop" >> $GITHUB_ENV

    - name: Set env to production environment
      if: endsWith(github.ref, '/main')
      run: |
        echo "IMAGE_TAG=devpanel/starshot:main" >> $GITHUB_ENV
        
    - name: Commit and push the container state to Docker Hub
      run: |
        docker commit ${{ job.services.webserver.id }} ${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_TAG }}

    - name: Push to tag latest
      if: endsWith(github.ref, '/main')
      run: |
        docker commit ${{ job.services.webserver.id }} devpanel/starshot:latest
        docker push devpanel/starshot:latest