name: Docker build and push template
on:
  push:
    branches:
      - 'feature/*'
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: devpanel/php:8.3-base
      options: --user root
      ports:
        - 80:80
    defaults:
      run:
        shell: bash
        working-directory: /var/www/html
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Test connectivity
      run: curl -Is https://www.google.com
    
    - name: Go to app root
      run: |
        cd $WEB_ROOT

    - name: Check out code
      uses: actions/checkout@v4
      with:
        path: repo

    - name: Move repository
      run: |
        rm -rf /var/www/html
        mkdir -p /var/www/html
        mv /__w/starshot/starshot/repo/* /var/www/html
        mv /__w/starshot/starshot/repo/.* /var/www/html || true  # Moves hidden files, ignoring any errors if no hidden files exist

    - name: Setup Drupal
      run: |
        pwd 
        cd $APP_ROOT
        ls -al
        bash /scripts/apache-start.sh
        bash .devpanel/custom_package_installer.sh
        bash .devpanel/init.sh
      env:
        WEB_ROOT: '/var/www/html/web'
        DB_HOST: mysql
        DB_PORT: 3306
        DB_ROOT_PASSWORD: root
        DB_NAME: drupaldb
        DB_USER: user
        DB_PASSWORD: pass
