name: Docker build and push template
on:
  push:
    branches:
      - 'feature/*'
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: devpanel/php:8.3-base
      options: --user root
    defaults:
      run:
        shell: bash
        working-directory: /var/www/html
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: drupaldb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: PWD
      id: PWD
      run: |
        pwd 
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Drupal
      run: |
        echo $USER
        export 
      env:
        # Environment variables for connecting to MySQL
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_ROOT_PASSWORD: root
        DB_DATABASE: drupaldb
        DB_USER: user
        DB_PASSWORD: pass
